### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by airstyle** [electron-userland/electron-webpack-quick-start#12]
Just cloning the repo, yarn, and yarn dev and it seems not working on windows.

[Screen here](https://puu.sh/yuA1s/a06648dc93.png)

**Comment by SrKomodo** [comment]
That happens because Windows ignores casing when handling paths
For example `C:\Path\To\My\Project` is the same as `C:\path\to\my\project` for Windows
That is why you get the error saying `There are multiple modules with names that only differ in casing`
The only real way to fix it is to be consistent by making sure all your paths are lowercase and that you use the correct casing when using `cd` in the command prompt

**Comment by ad34** [comment]
I have a similar issue , but not related with paths because all my paths are lowercase

![image](https://user-images.githubusercontent.com/259763/34732896-e72b17e0-f566-11e7-8b4a-08dd04703bb1.png)
