### ISSUE TITLE
adding image faild in dist

### ISSUE THREAD

**Issue by deeeed** [electron-userland/electron-webpack-quick-start#4]
I am trying to add external asset after cloning the project.
It works well in dev, but as soon as I distribute the project it fails.
Here is what I do:
- copy image to src/main/icon.png
- add 1 line of code in createMainWindow
`app.dock.setIcon(__dirname + '/icon.png'); `
- yarn dist 

I suppose I need to explicitly tell that my image needs to be included in the build but it's unclear where I should specify it?

**Comment by develar** [comment]
Please [Using Static Assets](https://webpack.electron.build/using-static-assets). Please be aware of https://github.com/electron-userland/electron-webpack-quick-start/issues/2#issuecomment-333699611

**Comment by deeeed** [comment]
Actually I also tried using __static assets (and also fixing the prod from #2 )
But the error is the same, it is very easy to reproduce

**Comment by develar** [comment]
I will check now.

**Comment by develar** [comment]
Reproduced, working on fix.

**Comment by develar** [comment]
electron-webpack 1.8.0 allows you to forget any issue related to image addressing.

Just require image and create native image from it:

```js
import { nativeImage } from 'electron'

app.dock.setIcon(nativeImage.createFromDataURL(require('./icon.png')))
```

Issue reopened, because we need to check `__static ` approach.

**Comment by develar** [comment]
Info for developers: 

The only way for us to help users — force using `__static` or implemented `nativeImage.createFromDataURL` approach. The reason is simple — electron-builder  is not aware that images from `src/main` (and any other custom user location) should be copied to packed app. 

Yes — it is very easy for user to configure electron-builder `extraResources` and use `process.resourcesPath` (`__dirname` for dev mode, and `process.resourcesPath` for production) but... it is easy only when do you aware about it. 

In addition, electron-builder force users to use efficient asar packaging and so, we need to unpack static assets (it is another reason why image usage can work only in a dev mode).

Or we can somehow process `__dirname` but this task is not what I want to do (unnecessary complication).

So, I am going to check how `__static` works (should work, but users reported that doesn't) and document `nativeImage.createFromDataURL(require` approach.

Info for user — don't be scared :) we do our best to hide all complexity under the hood and still produce efficiently packed app.

**Comment by deeeed** [comment]
thanks, I will use the nartiveImage approach

**Comment by djalmaaraujo** [comment]
@develar Thanks for pointing this here, so in the case of the Tray icon, I can still use the root path or I should try to use __static? The problem is when the app is packed and the root images are gone.

**Comment by djalmaaraujo** [comment]
```js
const mb = menubar({
  index: url,
  showDockIcon: true,
  icon: nativeImage.createFromDataURL(require(`${app.getAppPath()}/IconTemplate.png`)),
  alwaysOnTop: true
})

```

This should work or only with ```tray.setImage(image)```?

**Comment by develar** [comment]
@djalmaaraujo `menubar` — it is Electron API or some lib?

**Comment by djalmaaraujo** [comment]
@develar This is a lib that uses ```Tray(image)``` under the hood.

https://github.com/maxogden/menubar

**Comment by djalmaaraujo** [comment]
@develar The issue here is simple. The webpack is not including the root files I need. Is this something we can tweak on webpack configuration? Basically, leave the *.png files or what ever file I need included in the bundle.

**Comment by djalmaaraujo** [comment]
@develar I was able to figured out using files.

```yaml
"files": [
      "static/**/*"
    ],
```

**Comment by ashokgelal** [comment]
I'm really confused with this whole deal - should we use `__static` or `nativeImage` approach?  The problem with __static is it never worked for me. It resolves to something like http://localhost/Users/ashokgelal/code/src/icon.png in dev and in production it still resolves to the same path (but without localhost i.e. file://localhost/Users/ashokgelal/code/src/icon.png

I'm fine with using nativeImage approach but I can figure out how to set the src attribute of an img tag using this approach. There's no documentation on this feature as well.
